POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Ricardo",
    "email": "hotmail@email.com",
    "password": "12345678"
}

###

GET http://localhost:3003/getUsers
Content-Type: application/json


